jumpstarter-driver-gpio: Add read method required by PowerInterface
This addresses the following issue:
TypeError: Can't instantiate abstract class PowerSwitch without an implementation
for abstract method 'read'

This adds the read method that will raise an exception because we can't
get this kind of data from a gpio.

Signed-off-by: Alexandre Bailon <abailon@baylibre.com>