fix: raise MissingDriverError for driver allow-list mismatches (#874)
Otherwise, when using a env var client config, we will get an unrelated
error like, when the user does not set `JMP_DRIVERS_UNSAFE=true` or
`JMP_DRIVERS_ALLOW="UNSAFE"`

```shell
$ jmp shell -l video=true,enabled=true,firmware=es21 --duration 1h
[07/10/26 10:17:01] INFO     [jumpstarter.client.lease] Acquiring lease 019f4ae3-0d14-7b6e-8de2-68dad96972a3 for selector video=true,enabled=true,firmware=es21 for duration 1:00:00
[07/10/26 10:17:02] INFO     Waiting for ready connection at /var/folders/4m/llxcfbf1431fz8bjyr5cxtgr0000gn/T/jumpstarter-dfsi03r_/socket
[07/10/26 10:17:03] INFO     Releasing Lease 019f4ae3-0d14-7b6e-8de2-68dad96972a3
Error: Connection to exporter lost
```

with this change:
```shell
$ jmp shell -l video=true,enabled=true,firmware=es21 --duration 1h
[07/10/26 10:16:48] INFO     [jumpstarter.client.lease] Acquiring lease 019f4ae2-d828-76e4-865e-1017ef2dc5d8 for selector video=true,enabled=true,firmware=es21 for duration 1:00:00
                    INFO     Waiting for ready connection at /var/folders/4m/llxcfbf1431fz8bjyr5cxtgr0000gn/T/jumpstarter-4plbwien/socket
[07/10/26 10:16:50] WARNING  [jumpstarter.client.client] Driver client 'jumpstarter_driver_snmp.client.SNMPServerClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_pyserial.client.PySerialClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_pyserial.client.PySerialClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_pyserial.client.PySerialClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_network.client.NetworkClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_pyserial.client.PySerialClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_ustreamer.client.UStreamerClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_pyserial.client.PySerialClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_opendal.client.OpendalClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_pyserial.client.PySerialClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_pyserial.client.PySerialClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_shell.client.ShellClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_network.client.NetworkClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_network.client.NetworkClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_network.client.NetworkClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_network.client.NetworkClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_ridesx.client.RideSXPowerClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_ridesx.client.RideSXPowerClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_ssh.client.SSHWrapperClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_ssh.client.SSHWrapperClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_tmt.client.TMTClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_vnc.client.VNClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_ridesx.client.RideSXClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_composite.client.CompositeClient' is not available.
                    WARNING  Driver client 'jumpstarter_driver_composite.client.CompositeClient' is not available.
                    INFO     [jumpstarter_cli.shell] Waiting for beforeLease hook to complete...
                    INFO     [jumpstarter.client.status_monitor] Status changed: None -> LEASE_READY (version=2)
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
jumpstarter⚡qti-snapdragon-ride4-sa8775p-22➤
```

and when the user tries to use `j`:
```
│ │ ╰──────────────────────────────────────────────────────────────────────────────────────────╯ │ │
│ │ ImportError: Driver 'jumpstarter_driver_composite.client.CompositeClient' is not installed.  │ │
│ │                                                                                              │ │
│ │ This usually indicates a version mismatch between your client and the exporter.              │ │
│ │ Please try to update your client to the latest version and ensure the exporter has the       │ │
│ │ correct version installed.                                                                   │ │
```

Signed-off-by: Benny Zlotnik <bzlotnik@redhat.com>
(cherry picked from commit de9f4fd27f217ecff9ef0dde92345fd2975b8d61)